// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPx4Z4-JEjOqAElVfrtkP-hCe113Rx40Y',
    appId: '1:931580021786:web:194a79f73d6618734695a3',
    messagingSenderId: '931580021786',
    projectId: 'dagym-3a2e3',
    authDomain: 'dagym-3a2e3.firebaseapp.com',
    storageBucket: 'dagym-3a2e3.appspot.com',
    measurementId: 'G-XY1XM2H896',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Wch_5pi11MBhRi6X2uPDzepfspefXpQ',
    appId: '1:931580021786:android:99824b835b5b788a4695a3',
    messagingSenderId: '931580021786',
    projectId: 'dagym-3a2e3',
    storageBucket: 'dagym-3a2e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATnuy5b2apgaGvsMJaIR7LxWa-_D65q_w',
    appId: '1:931580021786:ios:9f5c0bad129de5c14695a3',
    messagingSenderId: '931580021786',
    projectId: 'dagym-3a2e3',
    storageBucket: 'dagym-3a2e3.appspot.com',
    iosClientId: '931580021786-adi03qc9reum790lq7hj74s4m745e6s4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gym',
  );
}
